### ISSUE TITLE
Top border on first relevant product shouldn't be there.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Green-Top-Energy-Shop#3]
First item has top border but it serves no purpose. There's no content to separate with. This needs to be fixed.
![screenshot from 2016-02-25 12-21-28](https://cloud.githubusercontent.com/assets/1911594/13318299/518b6ff4-dbba-11e5-8e34-4b7b88c71a4d.png)

**Comment by talrez11** [comment]
Fixed
