### ISSUE TITLE
Related item controls need improvement.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Green-Top-Energy-Shop#4]
Related items on checkout need to be improved:
- [ ] Controls need to be bigger and easier to click;
- [ ] Mouse cursor is regular text selection (I-beam) cursor, needs to be link pointer;
- [ ] Title for related item needs to be aligned to the left (or right on RTL languages);
- [ ] Price needs to include currency;
- [ ] Remove colon (`:`) from last related 

![screenshot from 2016-02-25 12-23-00](https://cloud.githubusercontent.com/assets/1911594/13318352/88f42de6-dbba-11e5-9d24-c4b7828c6ed5.png)

**Comment by talrez11** [comment]
Fixed
